apiVersion: v2
name: deployhub
description: DeployHub Pro
home: https://www.deployhub.com
icon: https://deployhubproject.github.io/DeployHub-Pro/deployhub.svg
keywords:
- Service Catalog
- Microservices
- SBOM
type: application
version: 10.0.415
appVersion: 10.0.0
dependencies:
- name: ms-general
  version: 11.0.815
  repository: https://deployhubproject.github.io/charts/
- name: ms-nginx
  version: 11.0.815
  repository: https://deployhubproject.github.io/charts/
- name: ms-ui
  version: 11.0.815
  repository: https://deployhubproject.github.io/charts/
- name: ms-compitem-crud
  version: 10.0.1566
  repository: https://ortelius.github.io/ms-compitem-crud/
- name: ms-dep-pkg-cud
  version: 10.0.1670
  repository: https://ortelius.github.io/ms-dep-pkg-cud/
- name: ms-dep-pkg-r
  version: 10.0.1705
  repository: https://ortelius.github.io/ms-dep-pkg-r/
- name: ms-postgres
  version: 10.0.463
  repository: https://ortelius.github.io/ms-postgres/
  condition: global.postgresql.enabled
- name: ms-sbom-export
  version: 10.0.933
  repository: https://ortelius.github.io/ms-sbom-export/
- name: ms-scorecard
  version: 10.0.1276
  repository: https://ortelius.github.io/ms-scorecard/
- name: ms-textfile-crud
  version: 10.0.1635
  repository: https://ortelius.github.io/ms-textfile-crud/
- name: ms-validate-user
  version: 10.0.1694
  repository: https://ortelius.github.io/ms-validate-user/
- name: scec-arangodb
  version: 11.0.4
  repository: https://ortelius.github.io/scec-arangodb/
- name: scec-deppkg
  version: 11.0.1136
  repository: https://ortelius.github.io/scec-deppkg/
- name: scec-vulnerability
  version: 11.0.1354
  repository: https://ortelius.github.io/scec-vulnerability/
